[package]
name = "rust-tuikit-bg-draw"
version = "0.1.0"
authors = ["Alwyn Nixon-Lloyd <32872980+zarquin@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tuikit = "*"
